# syntax=docker/dockerfile:1
FROM debian:12

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
        apt-get -y --force-yes install \
        ca-certificates \
        nano \
        coreutils \
        libasan6 \
        libasan8 \
        clang-13 clang-14 \
        libclang-rt-dev
