name: debian-12

on:
  push:
  pull_request:

jobs:
    compile:
        name: debian test
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v3
          - name: Run test
            uses: addnab/docker-run-action@v3
            with:
                image: debian:12
                options: -v ${{ github.workspace }}:/work
                run: |
                    apt-get update && \
                    DEBIAN_FRONTEND=noninteractive \
                    apt-get install -y --no-install-recommends \
                    ca-certificates \
                    clang-13 clang-14
                    id;ls -al /work/; # compile command here
                    clang-14 -O0 -g a.c  -fsanitize=address   -fsanitize-recover=address -o b
                    ./a;./a;./a;./a;./a;./a;./a;./a;./a;./a
